name: Build and Push Container to Docker Hub

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [ "master" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Build and Push Container to docker.io
        uses: GlueOps/github-actions-build-push-containers@v0.3.5
        with:
          registry: "docker.io"
          dockerhub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
          dockerhub_password: ${{ secrets.DOCKER_HUB_TOKEN }}
          registry-username: ${{ secrets.DOCKER_HUB_USERNAME }}
