name: build

on:
  pull_request: {}
  release: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup qemu
        uses: docker/setup-qemu-action@v1
      - name: setup buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: build
        run: |
          docker build .
